spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Freedom@0
    driver-class-name: com.mysql.cj.jdbc.Driver

    flyway:
      enabled: true
      locations: classpath:db/migration
  jpa:
    show-sql: true